version: '3.9'
services:
    postgres:
        container_name: airflow-database
        image: postgres:16.3
        platform: linux/arm64
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - POSTGRES_HOST_AUTH_METHOD=md5
        logging:
            options:
                max-size: 10m
                max-file: "3"

    webserver:
        container_name: airflow-webserver
        image: ppatcoding/airflow:latest
        platform: linux/arm64
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
